name: Project Setup
description: Setup Python and Poetry
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@5db1cf9a59fb97c40a68accab29236f0da7e94db # v5.6.0
      with:
        python-version: 3.12.x
    - name: Poetry Setup
      uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1
      with:
        version: 2.1.3
    - name: Install Dependencies
      shell: bash
      run: poetry install
