version: 2.1

executors:
  changelog-linter:
    working_directory: /home/circleci/project
    docker:
      - image: circleci/golang:1.9.6

jobs:
  check-black:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - restore_cache:
          key: v3-python-requirements-black
      - run:
          name: Install Black
          command: |
            virtualenv ~/venv-black
            . ~/venv-black/bin/activate
            pip install black==19.10b0
      - save_cache:
          key: v3-python-requirements-black
          paths:
            - "~/venv-black"
      - run:
          name: Run Black check
          command: |
            . ~/venv-black/bin/activate
            black --check .
  changelog-lint:
    executor: changelog-linter
    steps:
      - checkout
      - run:
          name: Install rcmachado/changelog
          command: |
            curl -s https://api.github.com/repos/rcmachado/changelog/releases/latest \
            | grep "browser_download_url.*linux_amd64" \
            | cut -d : -f 2,3 \
            | tr -d \" \
            | wget -qi -
            tar xvf changelog_*_linux_amd64.tar.gz changelog
            mv changelog /go/bin/
      - run:
          name: Lint changelog
          command: |
            diff CHANGELOG.md <(changelog fmt CHANGELOG.md) --color -u
  build:
    working_directory: ~/scanapi
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python setup.py develop
            pip install -e .[dev] .[test]
      - run:
          name: Run tests
          command: ./venv/bin/pytest --cov=./scanapi --cov-report=xml
      - run:
          name: Upload coverage report to codecov.io
          command: ./venv/bin/codecov

workflows:
  version: 2
  master:
    jobs:
      - check-black
      - changelog-lint
      - build
