name: Run ScanAPI Examples Suite
description: Setup the environment and run the documented examples against the current package
runs:
  using: composite
  steps:
    - name: Run Project Setup
      uses: ./.github/actions/setup

    - name: Checkout ScanAPI Examples repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: scanapi/examples
        path: examples

    - name: Run PokeAPI example
      shell: bash
      run: uv run scanapi run ./examples/pokeapi/scanapi.yaml -c ./examples/pokeapi/scanapi.conf -o pokeapi.html

    - name: Upload PokeAPI ScanAPI Report
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: ${{ always() }}
      with:
        name: PokeAPI ScanAPI Report
        path: pokeapi.html

    - name: Run httpbingo example
      shell: bash
      run: uv run scanapi run ./examples/httpbingo-api/httpbingo.yaml -c ./examples/httpbingo-api/scanapi.conf -o httpbingo.html

    - name: Upload httpbingo ScanAPI Report
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: ${{ always() }}
      with:
        name: httpbingo.org ScanAPI Report
        path: httpbingo.html

    - name: Run Demo API example
      shell: bash
      env:
        BASE_URL: "https://demo-api.fly.dev/api/v1/"
        USER: "scanapi-workflow"
        PASSWORD: Q*jW@p8pVmHwm2RwQd8ZR8LK
      run: uv run scanapi run ./examples/demo-api/scanapi.yaml -c ./examples/demo-api/scanapi.conf -o demo-api.html

    - name: Upload Demo API ScanAPI Report
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: ${{ always() }}
      with:
        name: Demo API ScanAPI Report
        path: demo-api.html
