name: Publish dev

on:
  push:
    branches:
      - main
permissions:
  contents: read
  pull-requests: write

jobs:
  build-n-publish-pypi:
    if: github.repository == 'scanapi/scanapi'
    name:  Build and publish Python 🐍 distributions 📦
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ScanAPI repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v5.6.0
        with:
          python-version: 3.12.x
      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 #v9.0.0
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      - name: Install Dependencies
        run: uv sync --extra dev --prerelease=allow
      - name: Run pre-release version update
        run: |
          make change-version-dev
      - name: Build and publish to pypi
        run: |
          uv build
          uv publish --token ${{ secrets.PYPI_TOKEN }}

  test-examples:
    name: Test Examples
    runs-on: ubuntu-latest
    needs:
      - build-n-publish-pypi
    steps:
      - name: Checkout ScanAPI repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install dev version of ScanAPI
        run: pip install scanapi==${{ env.VERSION }}
      - name: Run examples
        uses: ./.github/actions/run_examples_suite
 