name: Update Version

on:
  pull_request:
  

permissions:
  contents: read
  pull-requests: write

jobs:
  update-version:
    if: github.repository == 'scanapi/scanapi'
    name: Update Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ScanAPI repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Run version update
        run: |
          make change-version-alpha
